---
title: "tidyverse_tutorial_1"
output: html_document
---

```{r}
install.packages("tidymodels")

install.packages("broom.mixed")

install.packages("dotwhisker")

install.packages("readr")

install.packages("rstanarm")
```

```{r}
library(tidymodels)

library(broom.mixed)

library(dotwhisker)

library(readr)
```


```{r}
urchins_trial <- read_csv("https://tidymodels.org/start/models/urchins.csv")

urchins_trial
```


```{r}
urchins <- read_csv("https://tidymodels.org/start/models/urchins.csv")%>%

setNames(c("food_regime", "initial_volume", "width"))%>%
  
mutate(food_regime = factor(food_regime, levels = c("Initial", "Low", "High")))

urchins
```


```{r}
ggplot(urchins,
       aes(x = initial_volume, 
           y = width, 
           group = food_regime, 
           col = food_regime)) + 
  geom_point() + 
  geom_smooth(method = lm, se = FALSE) +
  scale_color_viridis_d(option = "plasma", end = .7)
```


width ~ initial_volume * food_regime



```{r}
lm_mod <- 
  linear_reg() %>% 
  set_engine("lm") #creating the model



lm_fit <- 
  lm_mod %>% 
  fit(width ~ initial_volume * food_regime, data=urchins) #the formula mentioned above

lm_fit #model is estimated or trained
```



```{r}
tidy(lm_fit)
```

```{r}
tidy(lm_fit) %>% 
  dwplot(dot_args = list(size = 2, color = "black"),
         whisker_args = list(color = "black"),
         vline = geom_vline(xintercept = 0, colour = "grey50", linetype = 2))
```
















Using our model to predict

```{r}
new_points <- expand.grid(initial_volume = 20, 
                          food_regime = c("Initial", "Low", "High"))

new_points
```

```{r}
#mean values at each food regime
mean_pred <- predict(lm_fit, new_data = new_points)

mean_pred
```

```{r}
#confidence interval of mean values for each food regime
conf_int_pred <- predict(lm_fit, 
                         new_data = new_points, 
                         type = "conf_int")
conf_int_pred
```



```{r}
plot_data <- 
  new_points %>% 
  bind_cols(mean_pred) %>% 
  bind_cols(conf_int_pred)

plot_data
```

```{r}
ggplot(plot_data, aes(x = food_regime)) + 
  geom_point(aes(y = .pred)) + 
  geom_errorbar(aes(ymin = .pred_lower, 
                    ymax = .pred_upper),
                width = .2) + 
  labs(y = "urchin size")
```




















Model with a different engine
```{r}
prior_dist <- rstanarm::student_t(df = 1)

set.seed(123)


bayes_mod <-   
  linear_reg() %>% 
  set_engine("stan", 
             prior_intercept = prior_dist, 
             prior = prior_dist)


bayes_fit <- 
  bayes_mod %>% 
  fit(width ~ initial_volume * food_regime, data = urchins)

print(bayes_fit, digits = 5)

tidy(bayes_fit, conf.int = TRUE)
```



```{r}
bayes_plot_data <- 
  new_points %>% 
  bind_cols(predict(bayes_fit, new_data = new_points)) %>% 
  bind_cols(predict(bayes_fit, new_data = new_points, type = "conf_int"))

ggplot(bayes_plot_data, aes(x = food_regime)) + 
  geom_point(aes(y = .pred)) + 
  geom_errorbar(aes(ymin = .pred_lower, ymax = .pred_upper), width = .2) + 
  labs(y = "urchin size") + 
  ggtitle("Bayesian model with t(1) prior distribution")
```

